{% set name = "dvc" %}
{% set version = "0.40.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iterative/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3d99730ce8b5fdb2705e21411042e1c29a4dc35e1120f582f1cf5215dd5578d6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - git
    - azure-storage-blob==1.3.0
    - boto3==1.9.115
    - ply>=3.9 # See https://github.com/pyinstaller/pyinstaller/issues/1945
    - configparser>=3.5.0
    - zc.lockfile>=1.2.1
    - future>=0.16.0
    - google-cloud-storage==1.13.0
    - PyInstaller==3.4
    - colorama>=0.3.9
    - configobj>=5.0.6
    - networkx>=2.1
    - gitpython>=2.1.8
    - setuptools>=34.0.0
    - nanotime>=0.5.2
    - pyasn1>=0.4.1
    - schema>=0.6.7
    - paramiko>=2.4.1
    - jsonpath-ng>=1.4.3
    - requests>=2.18.4
    - wheel>=0.31.1
    - futures>=3.2.0; python_version == "2.7"
    - grandalf==0.6
    - pydot>=1.2.4
    - asciimatics>=1.10.0
    - distro>=1.3.0
    - appdirs>=1.4.3
    - treelib>=1.5.5
    - inflect>=2.1.0
    - humanize>=0.5.1
    - dulwich>=0.19.11
    - ruamel.yaml>=0.15.91
    - pathlib2==2.3.3; python_version == "2.7"
    - oss2==2.6.1

test:
  requires:
    - pytest>=4.4.0
    - pytest-timeout>=1.3.3
    - pytest-cov>=2.6.1
    - pytest-xdist>=1.26.1
    - pytest-mock>=1.10.4
    - flaky>=3.5.3
    - mock>=3.0.0
    - xmltodict>=0.11.0
    - awscli>=1.16.125
    - google-compute-engine
    - pywin32; sys_platform == 'win32'
    - Pygments  # required by collective.checkdocs
    - collective.checkdocs
    - black==19.3b0 ; python_version >= '3.6'
    - flake8
    - flake8-docstrings
    - jaraco.windows==3.9.2
    - mock-ssh-server >= 0.5.0
  imports:
    - dvc

about:
  home: https://dvc.org
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Git for data scientists - manage your code and data together'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <http://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  doc_url: https://dvc.org/doc
  dev_url: https://github.com/iterative/dvc

extra:
  recipe-maintainers:
    - ei-grad
    - efiop
